### ISSUE TITLE
when i try to install gitrob..this error happen..

### ISSUE THREAD

**Issue by sonahri** [michenriksen/gitrob#102]

**Comment by perfecto25** [comment]
Im getting similar error installing on centos7 ruby v 2.2.1

"gcc -E -I/root/.rbenv/versions/2.2.1/include/ruby-2.2.0/x86_64-linux -I/root/.rbenv/versions/2.2.1/include/ruby-2.2.0/ruby/backward -I/root/.rbenv/versions/2.2.1/include/ruby-2.2.0 -I. -I/root/.rbenv/versions/2.2.1/include     -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat  conftest.c -o conftest.i"
conftest.c:3:22: fatal error: libpq-fe.h: No such file or directory
 #include <libpq-fe.h>
                      ^
compilation terminated.
checked program was:

**Comment by perfecto25** [comment]
was able to resolve it like this, 

1. yum install libpqxx-devel
2. gem install gitrob

**Comment by attacker420** [comment]
Now facing this issue, can't go further without solving it :( 
While configuring the gitrob , it occured .. then i run the gitrob -h ..again this showed up.
i ignored and tried to use the tool..but all in vain
````
*] Preparing database...SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:4:in `<class:Assessment>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:1:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:140:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:4:in `<class:GithubAccessToken>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:1:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:141:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:4:in `<class:Owner>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:1:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:142:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:4:in `<class:Repository>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:1:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:143:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:4:in `<class:Blob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:1:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:144:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:4:in `<class:Flag>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:1:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:145:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:4:in `<class:Comparison>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:1:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:146:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
 done


````
