### ISSUE TITLE
Error/warning messages while running a scan

### ISSUE THREAD

**Issue by Os3r3um** [michenriksen/gitrob#117]
Hi, 

Got this tool installed and configured according to the described steps. However, while I'm trying to use it I do get this: 

```
[*] Preparing database...SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:4:in `<class:Assessment>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:140:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:4:in `<class:GithubAccessToken>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:141:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:4:in `<class:Owner>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:142:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:4:in `<class:Repository>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:143:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:4:in `<class:Blob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:144:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:4:in `<class:Flag>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:145:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:4:in `<class:Comparison>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:146:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
```

Any idea how to get rid of these? 

Thanks!

**Comment by UnitOne1by1** [comment]
Is it says ' Could not find command "_xxx" ' in the end?

**Comment by Vjay615** [comment]
Anyone able to fix this issue? I am still getting a bunch of : SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
