### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hanjian007** [michenriksen/gitrob#146]
_ __           __
  ___ _(_) /________  / /
 / _ `/ / __/ __/ _ \/ _ \
 \_, /_/\__/_/  \___/_.__/
/___/ by @michenriksen

gitrob v2.0.0-beta started at 2018-07-16T16:03:54+08:00
Loaded 91 signatures
Web interface available at http://127.0.0.1:9393
Gathering targets...
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc42042b700, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:73 +0x133
main.AnalyzeRepositories(0xc420138800)
	/Users/michael/go/src/github.com/michenriksen/gitrob/main.go:101 +0xd4
main.main()
	/Users/michael/go/src/github.com/michenriksen/gitrob/main.go:228 +0x42c

**Comment by hanjian007** [comment]
[root@localhost opt]# go version
go version go1.9.4 linux/amd64

**Comment by ykosaraju** [comment]
happens on go 1.10.3 as well

**Comment by mattyjones** [comment]
@derricksong @ykosaraju @hanjian007 Can you please pull the latest master from this [fork](https://github.com/mattyjones/gitrob) and confirm if the issue still exists when the correct token is passed in either by env variable or the flag. This project is no longer maintained so any further issues or bugs should be opened up in that new fork. Thanks!
