### ISSUE TITLE
-no-expand-orgs errors out

### ISSUE THREAD

**Issue by derricksong** [michenriksen/gitrob#166]
## Expected Behavior
Pointed gitrob at my organization with -no-expand-orgs on, expected it not to error

## Actual Behavior
Looks like a Go exception

## Steps to Reproduce the Problem
$ ./gitrob -no-expand-orgs dadc-nms
        _ __           __
  ___ _(_) /________  / /
 / _ `/ / __/ __/ _ \/ _ \
 \_, /_/\__/_/  \___/_.__/
/___/ by @michenriksen

gitrob v2.0.0-beta started at 2018-10-20T20:42:31-07:00
Loaded 91 signatures
Web interface available at http://127.0.0.1:9393
Gathering targets...
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc420289150, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:73 +0x133
main.AnalyzeRepositories(0xc420296000)
	/Users/michael/go/src/github.com/michenriksen/gitrob/main.go:101 +0xd4
main.main()
	/Users/michael/go/src/github.com/michenriksen/gitrob/main.go:228 +0x42c
## Specifications

  - Gitrob version: v2.0.0-beta
  - Operating system:       
      System Version: macOS 10.13.6 (17G65)
      Kernel Version: Darwin 17.7.0
  - Go version: Used the compiled binary

**Comment by mattyjones** [comment]
@derricksong This was a known bug caused by no token or an invalid one. There is an open issue for it at mattyjones/gitrob#7 as this project is no longer maintained.
