### ISSUE TITLE
panic: sync: negative WaitGroup counter 

### ISSUE THREAD

**Issue by j3ssie** [michenriksen/gitrob#168]
## Expected Behavior
I just want to run gitrob for testing purpose.
I'm sure that I'm created new token with full permissons and ran
```
export GITROB_ACCESS_TOKEN=MY_TOKEN
```
I also try couple different repo but still got same error.

## Actual Behavior
Raw log from my console with debug mode
```
root@j3ssie:~/go/bin# ./gitrob -debug https://github.com/Automattic/wp-calypso
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /stats                    --> github.com/michenriksen/gitrob/core.NewRouter.func1 (3 handlers)
[GIN-debug] GET    /findings                 --> github.com/michenriksen/gitrob/core.NewRouter.func2 (3 handlers)
[GIN-debug] GET    /targets                  --> github.com/michenriksen/gitrob/core.NewRouter.func3 (3 handlers)
[GIN-debug] GET    /repositories             --> github.com/michenriksen/gitrob/core.NewRouter.func4 (3 handlers)
[GIN-debug] GET    /files/:owner/:repo/:commit/*path --> github.com/michenriksen/gitrob/core.fetchFile (3 handlers)
        _ __           __
  ___ _(_) /________  / /
 / _ `/ / __/ __/ _ \/ _ \
 \_, /_/\__/_/  \___/_.__/
/___/ by @michenriksen

gitrob v2.0.0-beta started at 2018-11-10T00:48:20-05:00
Loaded 91 signatures
Web interface available at http://127.0.0.1:9393
Gathering targets...
[GIN-debug] Listening and serving HTTP on 127.0.0.1:9393
 Error retrieving information on https://github.com/Automattic/wp-calypso: GET https://api.github.com/users/https://github.com/Automattic/wp-calypso: 404 Not Found []
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc420404190, 0xffffffffffffffff)
	/usr/lib/go-1.10/src/sync/waitgroup.go:73 +0x133
main.GatherRepositories(0xc42018a700)
	/root/go/src/github.com/michenriksen/gitrob/main.go:55 +0xa8
main.main()
	/root/go/src/github.com/michenriksen/gitrob/main.go:231 +0x41c
```

## Specifications

  - Gitrob version: gitrob v2.0.0-beta
  - Operating system: Kali Linux lastest version
  - Go version: go version go1.10.4 linux/amd64

**Comment by chrisfishwood** [comment]
Hi @j3ssie 

I hit a similar issue. Turns out I was running `gitrob` incorrectly as I was trying to run it against a specific repo and not the organization or user.

`./gitrob https://github.com/j3ssie/Osmedeus` will fail with the error you pointed out (note the `404`), but `./gitrob j3ssie` works just fine and will pull all repos for your user.

Hope that helps.
