### ISSUE TITLE
error during using it

### ISSUE THREAD

**Issue by leroywomack** [michenriksen/gitrob#175]
gitrob v2.0.0-beta started at 2019-02-04T09:16:25+02:00
Loaded 91 signatures
Web interface available at http://127.0.0.1:9393
Gathering targets...
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc42022b090, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:73 +0x133
main.AnalyzeRepositories(0xc42013c800)
	/Users/michael/go/src/github.com/michenriksen/gitrob/main.go:101 +0xd4
main.main()
	/Users/michael/go/src/github.com/michenriksen/gitrob/main.go:228 +0x42c

**Comment by ali0818** [comment]
Check if you are scanning a repo url or username. 
Try with only user/organistaion
EX: gitrob github

**Comment by mattyjones** [comment]
@ali0818 @leroywomack This is due to no github token being present or an expired one. If you turn on debugging you will see a 401 http error. Please pull from this [fork](https://github.com/mattyjones/gitrob) as this project is no longer maintained and I will be taking it over.
