### ISSUE TITLE
panic: sync: negative WaitGroup counter 

### ISSUE THREAD

**Issue by VikzSharma** [michenriksen/gitrob#176]
success@success-X555LD:~/Desktop/BugBounty/tools/GithubCloner/$ gitrob org-name
        _ __           __
  ___ _(_) /________  / /
 / _ `/ / __/ __/ _ \/ _ \
 \_, /_/\__/_/  \___/_.__/
/___/ by @michenriksen

gitrob v2.0.0-beta started at 2019-02-23T11:50:56+05:30
Loaded 91 signatures
Web interface available at http://127.0.0.1:9393
Gathering targets...
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc42020ec20, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:73 +0x133
main.AnalyzeRepositories(0xc42028e000)
	/Users/michael/go/src/github.com/michenriksen/gitrob/main.go:101 +0xd4
main.main()
	/Users/michael/go/src/github.com/michenriksen/gitrob/main.go:228 +0x42c
success@success-X555LD:~/Desktop/BugBounty/tools/GithubCloner/$

**Comment by ali0818** [comment]
Check if you are scanning a repo URL or username.
Try with only user/organization
EX: gitrob github

**Comment by VikzSharma** [comment]
Did the same , for some repos it doesn't throw error & for some it throws the above error.

**Comment by spastichaawk** [comment]
Try capitalizing the organization — that worked for me.

**Comment by degilq** [comment]
hi we have same problem:

[root@sectools bot]# gitrob sodimac
        _ __           __
  ___ _(_) /________  / /
 / _ `/ / __/ __/ _ \/ _ \
 \_, /_/\__/_/  \___/_.__/
/___/ by @michenriksen

gitrob v2.0.0-beta started at 2019-09-26T07:52:50-03:00
Loaded 91 signatures
Web interface available at http://127.0.0.1:9393
Gathering targets...
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc4203ea0d0, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:73 +0x133
main.AnalyzeRepositories(0xc420146700)
	/Users/michael/go/src/github.com/michenriksen/gitrob/main.go:101 +0xd4
main.main()
	/Users/michael/go/src/github.com/michenriksen/gitrob/main.go:228 +0x42c

**Comment by mattyjones** [comment]
@degilq @spastichaawk @VikzSharma This is due to no credentials or the wrong credentials being entered. The error message is poor as it points to not having anything to scan. If you turn on debug and look on the line after Gathering Targets you will see 401. This means bad credentials, and you also see [] to show nothing was entered. There is a note to fix this and give a better message if this runs with no credentials.
