### ISSUE TITLE
panic: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by dzhenway** [michenriksen/gitrob#185]
Hey there and thank you for using the issue tracker!

## Checklist before filing an issue:

- [Y ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [N] Have a usage question? Ask your question on [StackOverflow](http://stackoverflow.com), [StackExchange Security](https://security.stackexchange.com) or similar platform.
- [N] Have an idea for a feature? Make sure that it hasn't been suggested before and describe your idea in detail.

## None of the above? create a bug report

Make sure to add **all the information needed to understand the bug** so that someone can help. If information is missing, the issue will be labeled with 'Needs more information' and closed until there is enough information.

## Steps to Reproduce the Problem

  1. gitrob "access token" "username"
  2. gitrob v2.0.0-beta started at 2019-08-29T17:41:43+07:00
Loaded 91 signatures
Web interface available at http://127.0.0.1:9393
Gathering targets...
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc042316770, 0xffffffffffffffff)
        /usr/local/go/src/sync/waitgroup.go:73 +0x13a
main.AnalyzeRepositories(0xc042262000)
        /Users/michael/go/src/github.com/michenriksen/gitrob/main.go:101 +0xdb
main.main()
        /Users/michael/go/src/github.com/michenriksen/gitrob/main.go:228 +0x433

## Specifications

  - Gitrob version: v2.0.0-beta
  - Operating system: Windows 10 Pro
  - Go version: go version go1.12.4 windows/amd64

**Comment by thr0cyte** [comment]
my arch also have this question

**Comment by ceylanb** [comment]
> my arch also have this question

+1

**Comment by mattyjones** [comment]
@ceylanb @thr0cyte @dzhenway This is due to no or a wrong auth token. The error message is poor and misleading and leads to the fact that there are no targets. If you turn on debug you should be able to see you are getting a 401 which points to bad auth. Can you pull this [fork](https://github.com/mattyjones/gitrob) and try again. If the issue still persists then can you please open an issue in the fork and I will take a deeper look into this. Thanks!
