### ISSUE TITLE
error using gitrob 

### ISSUE THREAD

**Issue by kirtiso** [michenriksen/gitrob#191]
root@kali:~/go/src/github.com/michenriksen/gitrob$ go run main.go -github-access-token token vale google.com
        _ __           __
  ___ _(_) /________  / /
 / _ `/ / __/ __/ _ \/ _ \
 \_, /_/\__/_/  \___/_.__/
/___/ by @michenriksen

gitrob v2.0.0-beta started at 2020-02-23T02:14:58-05:00
Loaded 91 signatures
Web interface available at http://127.0.0.1:9393
Gathering targets...
 Error retrieving information on gopro.com: GET https://api.github.com/users/google.com: 401 Bad credentials []
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc0002de530, 0xffffffffffffffff)
	/usr/lib/go-1.13/src/sync/waitgroup.go:74 +0x139
main.GatherRepositories(0xc00026e100)
	/home/root/go/src/github.com/michenriksen/gitrob/main.go:55 +0xa8
main.main()
	/home/root/go/src/github.com/michenriksen/gitrob/main.go:231 +0x456
exit status 2

Please help me to resolve issue.

**Comment by mattyjones** [comment]
This is due to no credentials or the wrong credentials being entered. The error message is poor as it points to not having anything to scan. If you look on the line after **Gathering Targets** you will see **401**. This means bad credentials, and you also see **[]** to show nothing was entered. There is a note to fix this and give a better message if this runs with no credentials.

**Comment by karbassi** [comment]
I believe you mean to tag @kirtiso, not me :)

**Comment by mattyjones** [comment]
@kirtiso This has been moved to the new repo mattyjones/gitrob#7
