### ISSUE TITLE
ERROR 404

### ISSUE THREAD

**Issue by oghenejivwe** [michenriksen/gitrob#204]
I keep getting an error 404 for any github repository i try to scan

Error retrieving information on github.com/paragonie/paseto: GET https://api.github.com/users/github.com/paragonie/paseto: 404 Not Found []
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc00027e1b0, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:74 +0x137
main.GatherRepositories(0xc00028e100)
	/root/work/src/github.com/michenriksen/gitrob/main.go:55 +0xa8
main.main()
	/root/work/src/github.com/michenriksen/gitrob/main.go:231 +0x3fd

**Comment by kherwata** [comment]
i got the same error

**Comment by cyberwr3nch** [comment]
and here I am with the same error
```bash
cyberwr3nch@asgard:/opt/tools/gitrob$ ./gitrob xxxx.com
        _ __           __
  ___ _(_) /________  / /
 / _ `/ / __/ __/ _ \/ _ \
 \_, /_/\__/_/  \___/_.__/
/___/ by @michenriksen

gitrob v2.0.0-beta started at 2021-01-11T18:37:28+05:30
Loaded 91 signatures
Web interface available at http://127.0.0.1:9393
Gathering targets...
 Error retrieving information on xxxx.com: GET https://api.github.com/users/xxxx.com: 404 Not Found []
panic: sync: negative WaitGroup counter

goroutine 1 [running]:
sync.(*WaitGroup).Add(0xc42044a1a0, 0xffffffffffffffff)
        /usr/local/go/src/sync/waitgroup.go:73 +0x133
main.GatherRepositories(0xc4202a6000)
        /Users/michael/go/src/github.com/michenriksen/gitrob/main.go:55 +0xa8
main.main()
        /Users/michael/go/src/github.com/michenriksen/gitrob/main.go:227 +0x41c
```
