### ISSUE TITLE
gitrob config does not exit 

### ISSUE THREAD

**Issue by tomdavidson** [michenriksen/gitrob#70]
gitrob config does not exit from GitHub access token question:

```
Enter GitHub access tokens (blank line to stop):
sdfas
Enter GitHub access tokens (blank line to stop):

Enter GitHub access tokens (blank line to stop):

Enter GitHub access tokens (blank line to stop):

Enter GitHub access tokens (blank line to stop):

Enter GitHub access tokens (blank line to stop):

Enter GitHub access tokens (blank line to stop):

Enter GitHub access tokens (blank line to stop):

Enter GitHub access tokens (blank line to stop):
blank  
Enter GitHub access tokens (blank line to stop):
^C/usr/local/bundle/gems/highline-1.7.8/lib/highline.rb:869:in `eof?': Interrupt
        from /usr/local/bundle/gems/highline-1.7.8/lib/highline.rb:869:in `get_line'
        from /usr/local/bundle/gems/highline-1.7.8/lib/highline.rb:891:in `get_response'
        from /usr/local/bundle/gems/highline-1.7.8/lib/highline.rb:264:in `ask'
        from /usr/local/bundle/gems/highline-1.7.8/lib/highline.rb:779:in `gather'
        from /usr/local/bundle/gems/highline-1.7.8/lib/highline.rb:254:in `ask'
        from /usr/local/bundle/gems/gitrob-1.1.0/lib/gitrob/cli/commands/configure.rb:90:in `gather_access_tokens'
        from /usr/local/bundle/gems/gitrob-1.1.0/lib/gitrob/cli/commands/configure.rb:52:in `gather_configuration'
        from /usr/local/bundle/gems/gitrob-1.1.0/lib/gitrob/cli/commands/configure.rb:16:in `initialize'
        from /usr/local/bundle/gems/gitrob-1.1.0/lib/gitrob/cli/command.rb:7:in `new'
        from /usr/local/bundle/gems/gitrob-1.1.0/lib/gitrob/cli/command.rb:7:in `start'
        from /usr/local/bundle/gems/gitrob-1.1.0/lib/gitrob/cli.rb:95:in `configure'
        from /usr/local/bundle/gems/gitrob-1.1.0/lib/gitrob/cli.rb:51:in `initialize'
        from /usr/local/bundle/gems/thor-0.19.1/lib/thor.rb:355:in `new'
        from /usr/local/bundle/gems/thor-0.19.1/lib/thor.rb:355:in `dispatch'
        from /usr/local/bundle/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/bundle/gems/gitrob-1.1.0/exe/gitrob:5:in `<top (required)>'
        from /usr/local/bundle/bin/gitrob:22:in `load'
        from /usr/local/bundle/bin/gitrob:22:in `<main>'

```

**Comment by michenriksen** [comment]
Hi Tom, 

The configuration wizard expects to get at least one string with the correct syntax for an access token. 

Is there a use case for running the configuration wizard without entering access tokens?

**Comment by tomdavidson** [comment]
I was trying to create a .gitrobrc file just so I could see what it is suppose to look like, but I just tried again with a properly formated token and observed the same (this is in the same environment as #71):

```
Enter PostgreSQL hostname: |localhost| 
Enter PostgreSQL port: |5432| 
Enter PostgreSQL username: |gitrob| 
Enter PostgreSQL password (masked): 
Enter PostgreSQL database name: |gitrob| 
Enter GitHub access tokens (blank line to stop):
ba86b6249ff2ae8fa33a3f6292e4b182

Enter GitHub access tokens (blank line to stop):

Enter GitHub access tokens (blank line to stop):

Enter GitHub access tokens (blank line to stop):
```

**Comment by tomdavidson** [comment]
I just tried with my real token and realized the previous dummy token was not the correct length. Works as expected with the correct length of token.
