### ISSUE TITLE
check_conflict_version with Rack

### ISSUE THREAD

**Issue by sabsowitz** [michenriksen/gitrob#75]
After running `gitrob configure` I receive the following:

`/usr/lib/ruby/2.3.0/rubygems/specification.rb:2276:in`check_version_conflict': can't activate rack-2.0.1, already activated rack-1.6.4 (Gem::LoadError)
    from /usr/lib/ruby/2.3.0/rubygems/specification.rb:1403:in `activate'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:89:in`block in require'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `each'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in`require'
    from /usr/lib/ruby/vendor_ruby/sinatra/base.rb:2:in `<top (required)>'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in`require'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
    from /var/lib/gems/2.3.0/gems/gitrob-1.1.0/lib/gitrob/web_app.rb:1:in`<top (required)>'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in`require'
    from /var/lib/gems/2.3.0/gems/gitrob-1.1.0/lib/gitrob.rb:18:in `<top (required)>'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in`require'
    from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
    from /var/lib/gems/2.3.0/gems/gitrob-1.1.0/exe/gitrob:3:in`<top (required)>'
    from /usr/local/bin/gitrob:23:in `load'
    from /usr/local/bin/gitrob:23:in`<main>

I'm running Kali Linux and using Ruby 2.3.

**Comment by sabsowitz** [comment]
The issue appears to be with `load Gem.bin_path('gitrob', 'gitrob', version)`. However, I'm not sure how to modify this line.
