### ISSUE TITLE
gitrob configure

### ISSUE THREAD

**Issue by arbazhussain149** [michenriksen/gitrob#81]
root@arbaz:~# gitrob configure
/var/lib/gems/2.1.0/gems/github_api-0.14.4/lib/github_api/api.rb:301:in `namespace': namespace 'say' is already defined (ArgumentError)
	from /var/lib/gems/2.1.0/gems/github_api-0.14.4/lib/github_api/client.rb:61:in `<class:Client>'
	from /var/lib/gems/2.1.0/gems/github_api-0.14.4/lib/github_api/client.rb:4:in `<module:Github>'
	from /var/lib/gems/2.1.0/gems/github_api-0.14.4/lib/github_api/client.rb:3:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/github_api-0.14.4/lib/github_api.rb:78:in `block in require_all'
	from /var/lib/gems/2.1.0/gems/github_api-0.14.4/lib/github_api.rb:77:in `each'
	from /var/lib/gems/2.1.0/gems/github_api-0.14.4/lib/github_api.rb:77:in `require_all'
	from /var/lib/gems/2.1.0/gems/github_api-0.14.4/lib/github_api.rb:113:in `<module:Github>'
	from /var/lib/gems/2.1.0/gems/github_api-0.14.4/lib/github_api.rb:15:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/gitrob-1.1.0/lib/gitrob.rb:9:in `<top (required)>'
	from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/gitrob-1.1.0/exe/gitrob:3:in `<top (required)>'
	from /usr/local/bin/gitrob:22:in `load'
	from /usr/local/bin/gitrob:22:in `<main>'

Kali linux 2.0  ,  gem version : 2.6.6

**Comment by arbazhussain149** [comment]
Just Solved By Adding : 

gem uninstall github_api
gem install github_api -v 0.12
