### ISSUE TITLE
Permission denied @ rb_sysopen

### ISSUE THREAD

**Issue by rl6067** [michenriksen/gitrob#92]
Installed GitRob + all packages etc, configured it but when I try to run it with the command (example):

gitrob analyze acme.com then accept the disclaimer, I receive the following:

Do you agree to the terms of use? (y/n): y
/var/lib/gems/2.3.0/gems/gitrob-1.1.0/lib/gitrob/cli/commands/accept_terms_of_use.rb:50:in `initialize': Permission denied @ rb_sysopen - /var/lib/gems/2.3.0/gems/gitrob-1.1.0/agreement.txt (Errno::EACCES)
	from /var/lib/gems/2.3.0/gems/gitrob-1.1.0/lib/gitrob/cli/commands/accept_terms_of_use.rb:50:in `open'
	from /var/lib/gems/2.3.0/gems/gitrob-1.1.0/lib/gitrob/cli/commands/accept_terms_of_use.rb:50:in `accept_terms_of_use'
	from /var/lib/gems/2.3.0/gems/gitrob-1.1.0/lib/gitrob/cli/commands/accept_terms_of_use.rb:43:in `handle_user_input'
	from /var/lib/gems/2.3.0/gems/gitrob-1.1.0/lib/gitrob/cli/commands/accept_terms_of_use.rb:27:in `initialize'
	from /var/lib/gems/2.3.0/gems/gitrob-1.1.0/lib/gitrob/cli/command.rb:7:in `new'
	from /var/lib/gems/2.3.0/gems/gitrob-1.1.0/lib/gitrob/cli/command.rb:7:in `start'
	from /var/lib/gems/2.3.0/gems/gitrob-1.1.0/lib/gitrob/cli.rb:105:in `accept_tos'
	from /var/lib/gems/2.3.0/gems/gitrob-1.1.0/lib/gitrob/cli.rb:83:in `analyze'
	from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
	from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
	from /usr/lib/ruby/vendor_ruby/thor.rb:359:in `dispatch'
	from /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
	from /var/lib/gems/2.3.0/gems/gitrob-1.1.0/exe/gitrob:5:in `<top (required)>'
	from /usr/local/bin/gitrob:22:in `load'
	from /usr/local/bin/gitrob:22:in `<main>'

**Comment by rl6067** [comment]
SOLVED. My bad. 

sudo chmod 777 /var/lib/gems/2.3.0/gems/gitrob-1.1.0/
